
name: 🐛 Bug
description: 不具合報告（必須項目あり）
title: "[Bug] "
labels: ["bug", "type:bug"]

body:
  - type: markdown
    attributes:
      value: |
        ❗ 不具合再現・修正のため、必須項目は必ず記入してください。

  - type: textarea
    attributes:
      label: 手順
      description: 不具合が発生するまでの手順を記載してください
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 発生現象
      description: 実際に発生している問題を記載してください
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期待動作
      description: 本来期待される動作を記載してください
    validations:
      required: true

  - type: input
    attributes:
      label: FWバージョン / コミット
      placeholder: "例: V0020 / a1b2c3d"
    validations:
      required: true

  - type: input
    attributes:
      label: 使用基板
      placeholder: "例: ES1 #01/#02"
    validations:
      required: true

  - type: input
    attributes:
      label: 使用端末
      placeholder: "例: Pixel 7 (Android ver. 14)"
    validations:
      required: true


  - type: textarea
    attributes:
      label: 補足
      description: 他機種・他環境での発生有無やログ、スクリーンショット、その他情報があれば記載してください
    validations:
      required: false
