
name: ✨ Enhancement
description: 新機能・改善提案
labels: ["enhancement", "type:enhancement"]

body:
  - type: textarea
    attributes:
      label: 概要
      description: 実現したいことを簡潔に記載してください
    validations:
      required: true

  - type: textarea
    attributes:
      label: 補足
      description: 調査内容や参考情報があれば記載してください
    validations:
      required: false
